from z3 import *
solver=Solver()
c = Int("c")
m = Int("m")
k = Int("k")
size = Int("size")
array = Int("array")
a = Int("a")
arr = Int("arr")
b = Int("b")
i = Int("i")
j = Int("j")
index = Int("index")
temp = Int("temp")
argc = Int("argc")
rhs = Int("rhs")
argv = Int("argv")
u = Int("u")
DRD_RANDOM_VAR = Int("DRD_RANDOM_VAR")
N = Int("N")
solver.add(N == 100)
waws = False

r_arr_index_0_0 = Int("r_arr_index_0_0")
r_arr_index_0_1 = Int("r_arr_index_0_1")
r_arr_index_0_2 = Int("r_arr_index_0_2")
r_arr_index_0_3 = Int("r_arr_index_0_3")
i_drdVar_19 = Int("i_drdVar_19")
k_drdVar_19 = Int("k_drdVar_19")
j_drdVar_19 = Int("j_drdVar_19")
m_drdVar_19 = Int("m_drdVar_19")
solver.add((m_drdVar_19>=0),(m_drdVar_19<5))
i_drdVar_18 = Int("i_drdVar_18")
j_drdVar_18 = Int("j_drdVar_18")
k_drdVar_18 = Int("k_drdVar_18")
m_drdVar_18 = Int("m_drdVar_18")
solver.add((m_drdVar_18>=0),(m_drdVar_18<5))
i_drdVar_2 = Int("i_drdVar_2")
solver.add((k_drdVar_19>=1),(k_drdVar_19<c))
solver.add((k_drdVar_18>=1),(k_drdVar_18<c))
solver.add((j_drdVar_19>=1),(j_drdVar_19<b))
solver.add((j_drdVar_18>=1),(j_drdVar_18<b))
solver.add()
r_cond_0_0 = And (r_arr_index_0_0 == i_drdVar_18, True)
r_cond_0_1 = And (r_arr_index_0_1 == j_drdVar_18, True)
r_cond_0_2 = And (r_arr_index_0_2 == k_drdVar_18, True)
r_cond_0_3 = And (r_arr_index_0_3 == m_drdVar_18, True)
r_arr_index_1_0 = Int("r_arr_index_1_0")
r_arr_index_1_1 = Int("r_arr_index_1_1")
r_arr_index_1_2 = Int("r_arr_index_1_2")
r_arr_index_1_3 = Int("r_arr_index_1_3")
r_cond_1_0 = And (r_arr_index_1_0 == i_drdVar_19 - 1, True)
r_cond_1_1 = And (r_arr_index_1_1 == j_drdVar_19, True)
r_cond_1_2 = And (r_arr_index_1_2 == k_drdVar_19, True)
r_cond_1_3 = And (r_arr_index_1_3 == m_drdVar_19, True)
r_arr_index_2_0 = Int("r_arr_index_2_0")
r_cond_2_0 = And (r_arr_index_2_0 == 2, True)
raws = False
cstrnts = Or(waws,raws)
solver.add(cstrnts)
if solver.check() == z3.sat:
	print("seems like data race(waw/raw/war) exists within the loop!")
else:
	print("seems like no data race exists (please double check)")
